### ISSUE TITLE
Powershell 7 crashes when exiting from elixir's iex

### ISSUE THREAD

**Issue by SchrodingerZhu** [PowerShell/PowerShell#11215]
Step:
enter iex by `zsh -c 'iex'`, doube enter Ctrl-C to quit iex.
Behavior:
```
❯ zsh -c 'iex'
Erlang/OTP 22 [erts-10.5] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

warning: the VM is running with native name encoding of latin1 which may cause Elixir to malfunction as it expects utf8. Please ensure your locale is set to UTF-8 (which can be verified by running "locale" in your shell)
Interactive Elixir (1.9.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> 
BREAK: (a)bort (c)ontinue (p)roc info (i)nfo (l)oaded
       (v)ersion (k)ill (D)b-tables (d)istribution
^CProcess terminated. The process cannot access the file because it is being used by another process.
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(System.String, System.String[], Int32)
   at Microsoft.PowerShell.ManagedPSEntry.Main(System.String[])
System.IO.IOException: The process cannot access the file because it is being used by another process.
   at System.ConsolePal.TryGetCursorPosition(Int32& left, Int32& top, Boolean reinitializeForRead)
   at System.Console.get_CursorLeft()
   at Microsoft.PowerShell.ConsoleHostRawUserInterface.get_CursorPosition()
   at Microsoft.PowerShell.ConsoleHost.InputLoop.Run(Boolean inputLoopIsNested)
   at Microsoft.PowerShell.ConsoleHost.InputLoop.RunNewInputLoop(ConsoleHost parent, Boolean isNested)
   at Microsoft.PowerShell.ConsoleHost.EnterNestedPrompt()
   at Microsoft.PowerShell.ConsoleHost.DoRunspaceLoop(String initialCommand, Boolean skipProfiles, Collection`1 initialCommandArgs, Boolean staMode, String configurationName)
   at Microsoft.PowerShell.ConsoleHost.Run(CommandLineParameterParser cpp, Boolean isPrestartWarned)
   at Microsoft.PowerShell.ConsoleHost.Start(String bannerText, String helpText, String[] args)
   at Microsoft.PowerShell.ConsoleShell.Start(InitialSessionState initialSessionState, String bannerText, String helpText, String[] args)
   at Microsoft.PowerShell.ConsoleShell.Start(String bannerText, String helpText, String[] args)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(String consoleFilePath, String[] args, Int32 argc)

Warning: Program '/usr/bin/pwsh-preview' crashed.
```
Os info:
```
Linux ****** 5.3.12-arch1-1 #1 SMP PREEMPT Wed, 20 Nov 2019 19:45:16 +0000 x86_64 GNU/Linux
```

**Comment by iSazonov** [comment]
> the VM is running with native name encoding of latin1 which may cause Elixir to malfunction as it expects utf8.

What is locale in your session?

**Comment by SchrodingerZhu** [comment]
@iSazonov 
```
❯ locale
LANG=C
LC_CTYPE="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_PAPER="C"
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
LC_ALL=
schrodinger@Monad  ~                                                                                                                                                  [11:05]
❯ env LC_ALL=en_US.utf-8 iex
Erlang/OTP 22 [erts-10.5] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

Interactive Elixir (1.9.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> 
BREAK: (a)bort (c)ontinue (p)roc info (i)nfo (l)oaded
       (v)ersion (k)ill (D)b-tables (d)istribution
^CProcess terminated. The process cannot access the file because it is being used by another process.
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(System.String, System.String[], Int32)
   at Microsoft.PowerShell.ManagedPSEntry.Main(System.String[])
System.IO.IOException: The process cannot access the file because it is being used by another process.
   at System.ConsolePal.TryGetCursorPosition(Int32& left, Int32& top, Boolean reinitializeForRead)
   at System.Console.get_CursorLeft()
   at Microsoft.PowerShell.ConsoleHostRawUserInterface.get_CursorPosition()
   at Microsoft.PowerShell.ConsoleHost.InputLoop.Run(Boolean inputLoopIsNested)
   at Microsoft.PowerShell.ConsoleHost.InputLoop.RunNewInputLoop(ConsoleHost parent, Boolean isNested)
   at Microsoft.PowerShell.ConsoleHost.EnterNestedPrompt()
   at Microsoft.PowerShell.ConsoleHost.DoRunspaceLoop(String initialCommand, Boolean skipProfiles, Collection`1 initialCommandArgs, Boolean staMode, String configurationName)
   at Microsoft.PowerShell.ConsoleHost.Run(CommandLineParameterParser cpp, Boolean isPrestartWarned)
   at Microsoft.PowerShell.ConsoleHost.Start(String bannerText, String helpText, String[] args)
   at Microsoft.PowerShell.ConsoleShell.Start(InitialSessionState initialSessionState, String bannerText, String helpText, String[] args)
   at Microsoft.PowerShell.ConsoleShell.Start(String bannerText, String helpText, String[] args)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(String consoleFilePath, String[] args, Int32 argc)

```

**Comment by iSazonov** [comment]
@SchrodingerZhu Thanks! Please remove PSReadline (Remove-Module PSReadline) and try again. Also what is a terminal you use?

**Comment by SchrodingerZhu** [comment]
still
```
^CProcess terminated. The process cannot access the file because it is being used by another process.
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(System.String, System.String[], Int32)
   at Microsoft.PowerShell.ManagedPSEntry.Main(System.String[])
System.IO.IOException: The process cannot access the file because it is being used by another process.
   at System.ConsolePal.TryGetCursorPosition(Int32& left, Int32& top, Boolean reinitializeForRead)
   at System.Console.get_CursorLeft()
   at Microsoft.PowerShell.ConsoleHostRawUserInterface.get_CursorPosition()
   at Microsoft.PowerShell.ConsoleHost.InputLoop.Run(Boolean inputLoopIsNested)
   at Microsoft.PowerShell.ConsoleHost.InputLoop.RunNewInputLoop(ConsoleHost parent, Boolean isNested)
   at Microsoft.PowerShell.ConsoleHost.EnterNestedPrompt()
   at Microsoft.PowerShell.ConsoleHost.DoRunspaceLoop(String initialCommand, Boolean skipProfiles, Collection`1 initialCommandArgs, Boolean staMode, String configurationName)
   at Microsoft.PowerShell.ConsoleHost.Run(CommandLineParameterParser cpp, Boolean isPrestartWarned)
   at Microsoft.PowerShell.ConsoleHost.Start(String bannerText, String helpText, String[] args)
   at Microsoft.PowerShell.ConsoleShell.Start(InitialSessionState initialSessionState, String bannerText, String helpText, String[] args)
   at Microsoft.PowerShell.ConsoleShell.Start(String bannerText, String helpText, String[] args)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(String consoleFilePath, String[] args, Int32 argc)
```

**Comment by SchrodingerZhu** [comment]
same error with terminal `alacritty`.

**Comment by iSazonov** [comment]
>    at System.ConsolePal.TryGetCursorPosition(Int32& left, Int32& top, Boolean reinitializeForRead)
   at System.Console.get_CursorLeft()

I guess it is .Net Core issue with `alacritty`.  
@rjmholt Thoughts?

**Comment by rjmholt** [comment]
Looks like an issue with console ownership where PowerShell expects to own the console but does not.

Looks like the place we do this in PowerShell is [here](https://github.com/PowerShell/PowerShell/blob/d68d126cae263637a819a14f83062d63a6f221b0/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs#L2444-L2447). The underlying implementation of that property in *nix is [here](https://github.com/PowerShell/PowerShell/blob/d68d126cae263637a819a14f83062d63a6f221b0/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostRawUserInterface.cs#L1395-L1407).

It feels to me like PowerShell is trying to be too clever in this particular instance.

My simplified mental model for how our interactive shell should host another interactive program/shell is that we synchronously cede the console to the subprocess, and then when that subprocess finishes we take it back. I'm imagining that's the intended implementation, so this might be an issue where the ConHost is not waiting for that properly.

It is notable that we don't have this issue generally; just with `iex`. @SchrodingerZhu what happens if you execute `iex` directly, without `zsh`?

/cc @daxian-dbw and @SteveL-MSFT since they are better versed in our console interaction logic

**Comment by SteveL-MSFT** [comment]
It looks like the problem is that pwsh is sent a SIGTTIN signal (meaning pwsh doesn't have the console, so stop trying to read it), but it's not being handled.  I couldn't find how to handle this in .NET Core.

**Comment by rjmholt** [comment]
([Summary of currently evented signals in .NET Core](https://github.com/dotnet/corefx/issues/3188#issuecomment-365986835))

**Comment by SteveL-MSFT** [comment]
Looks like the recommend solution is to use a Mono library to handle this

**Comment by iSazonov** [comment]
Why not if it is small library.

**Comment by rjmholt** [comment]
> Why not if it is small library.

While I'd usually propose caution on bringing a new dependency in (both for size and dependency matching reasons), this one seems especially useful to have as a shell, so agree with the proposal.

**Comment by daxian-dbw** [comment]
`PSReadLine` is affected by this too. The call to `Console.ReadKey` will result in an `IOException` in this case.

I read a bit more about `SIGTTIN` and it looks to me the default action for this signal is what we want unless the reading process is ignoring or blocking this signal:

> From [Access to the Controlling Terminal](https://www.gnu.org/software/libc/manual/html_node/Access-to-the-Terminal.html#Access-to-the-Terminal)
When a process in a background job tries to read from its controlling terminal, the process group is usually sent a SIGTTIN signal. This normally causes all of the processes in that group to stop (unless they handle the signal and don’t stop themselves). However, if the reading process is ignoring or blocking this signal, then read fails with an EIO error instead.

And I found this PR: [Investigate which signals really need to be blocked on Unix](https://github.com/dotnet/coreclr/issues/3305), and [this comment](https://github.com/dotnet/coreclr/issues/3305#issuecomment-217895125) indicates `SIGTTIN` is handled by its default handler, which is `Stop` (suspend).

According to the description [here](http://curiousthing.org/sigttin-sigttou-deep-dive-linux#what-are-code-classprettyprintsigttincode-and_2), `SIGTTIN` is sent to a background process when it tries to read from the terminal and `SIGCONT` is sent when the background process is resumed. So I tried the following in bash on Linux:

```none
## run start-sleep first so it's guaranteed that '[Console]::CursorLeft' executes after the pwsh process becomes a background process.
pwsh-preview -c "start-sleep -s 2; Set-Content ~/bb.txt -value value; Add-Content ~/bb.txt -Value ([Console]::CursorLeft)" &
```
And here is the result
```none
bash:39> pwsh-preview -c "start-sleep -s 2; Set-Content ~/bb.txt -value value; Add-Content ~/bb.txt -Value ([Console]::CursorLeft)" &
[1] 12962
bash:40> cat ~/bb.txt 
value

[1]+  Stopped                 pwsh-preview -c "start-sleep -s 2; Set-Content ~/bb.txt -value value; Add-Content ~/bb.txt -Value ([Console]::CursorLeft)"
bash:41> cat ~/bb.txt 
value
bash:42> fg
pwsh-preview -c "start-sleep -s 2; Set-Content ~/bb.txt -value value; Add-Content ~/bb.txt -Value ([Console]::CursorLeft)"
bash:43> cat ~/bb.txt 
value
0
```
It looks to me `SIGTTIN` is handled properly -- `pwsh` was suspended when reaching `[Console]::CursorLeft` and resumed after `fg` brings it to foreground.
So maybe this is not caused by the handling of `SIGTTIN`? (it seems the default action should just be desired anyways)

**Comment by daxian-dbw** [comment]
Also want to add, this issue has a different repro **on WSL**, which doesn't involve `SIGTTIN` signal sending to pwsh:

![image](https://user-images.githubusercontent.com/127450/71133608-ef89cb80-21af-11ea-8771-d3f08aab5875.png)

Here, `iex` runs from bash, then type `Ctrl+C` twice to exit from it, then start `pwsh-preview`, and pwsh crashes with the same exception stack.

**Comment by SteveL-MSFT** [comment]
Related https://github.com/PowerShell/PowerShell/issues/8975

**Comment by SteveL-MSFT** [comment]
.NET team is not going to directly support this.  @JamesWTruher has a prototype to catch signals and convert to .NET event we can use.

**Comment by JamesWTruher** [comment]
Since current dotnet preview now contains code for handling signals, i created a private which handles `SIGTTIN` and `SIGTTOU`. Sadly, those signals are not getting delivered in this scenario (no surprise, these are really signals for job control environments which PS is _not_). On the plus side, i have been able to replicate the behavior in a powershell-free environment. I've opened https://github.com/dotnet/runtime/issues/59059 to see if the dotnet folks can provide some guidance.

**Comment by radrow** [comment]
The issue persists for me. However, I managed to workaround it by wraping `erl` or `iex` with [rlwrap](https://github.com/hanslub42/rlwrap). You may loose some autocompletion, but it is still better than shell crash...

**Comment by darthwalsh** [comment]
I ran into this issue by running a build script somebody had written that started with shebang `#!/bin/sh -eil` If the script fails, my entire terminal tab just disappears! (I guess the "close terminal on shell exit is a setting I can configure, but it's very confusing and disruptive.)

A minimal repro on my mac is running `bash -i something` will kills the current pwsh instance with a similar, but different `IOException: Input/output error` (leaving this breadcrumb here in case somebody else google finds this).

```
$ bash -i something
bash: something: No such file or directory
^[[7;1RProcess terminated. Input/output error
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(System.String[], Int32)
   at Microsoft.PowerShell.ManagedPSEntry.Main(System.String[])
System.IO.IOException: Input/output error
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at System.ConsolePal.TryGetCursorPosition(Int32& left, Int32& top, Boolean reinitializeForRead)
   at System.ConsolePal.GetCursorPosition()
   at System.Console.get_CursorLeft()
   at Microsoft.PowerShell.ConsoleHostRawUserInterface.get_CursorPosition()
   at Microsoft.PowerShell.ConsoleHost.InputLoop.Run(Boolean inputLoopIsNested)
   at Microsoft.PowerShell.ConsoleHost.InputLoop.RunNewInputLoop(ConsoleHost parent, Boolean isNested)
   at Microsoft.PowerShell.ConsoleHost.EnterNestedPrompt()
   at Microsoft.PowerShell.ConsoleHost.DoRunspaceLoop(String initialCommand, Boolean skipProfiles, Collection`1 initialCommandArgs, Boolean staMode, String configurationName, String configurationFilePath)
   at Microsoft.PowerShell.ConsoleHost.Run(CommandLineParameterParser cpp, Boolean isPrestartWarned)
   at Microsoft.PowerShell.ConsoleHost.Start(String bannerText, String helpText, Boolean issProvidedExternally)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(String[] args, Int32 argc)
[Process completed]
``` 

---

Since I'm not expecting this to be fixed anytime soon, is there some ugly workaround I can put into my powershell profile to prevent my shell process from dying? I tried "I'll start a second `pwsh`, so the outer pwsh process doesn't die," *but both pwsh processes crash* D: I googled around and hoped to find something with the terms "pwsh PosixSignal" but didn't find anything good.

**Comment by SteveL-MSFT** [comment]
Unfortunately we likely need .NET to make a change here to handle signals.  As for a workaround, I can't think of one if you need to explicitly have the nested shell interactive.  If you can not request it to be interactive, that would not expose the issue.

**Comment by SteveL-MSFT** [comment]
Unfortunately we likely need .NET to make a change here to handle signals.  As for a workaround, I can't think of one if you need to explicitly have the nested shell interactive.  If you can not request it to be interactive, that would not expose the issue.

**Comment by JamesWTruher** [comment]
i believe that this is actually a dotnet issue, and I've opened: https://github.com/dotnet/runtime/issues/59059 to track

**Comment by darthwalsh** [comment]
Having your shell process just crash feels pretty bad.

The issue seems to still be blocked on https://github.com/dotnet/runtime/issues/59059 (which was prioritized to top of backlog last release, but maybe needs another bump.)

**Comment by darthwalsh** [comment]
Maybe the runtime issue is hard to fix; would it be the right fix to add `try { } catch (IOException)` in powershell's code when using `System.Console` APIs?

[`Console.CursorLeft`](https://learn.microsoft.com/en-us/dotnet/api/system.console.cursorleft?view=net-8.0) is documented to throw `IOException` so even if https://github.com/dotnet/runtime/issues/59059 is fixed it would be great if other edge cases didn't crash your pwsh process.

**Comment by JamesWTruher** [comment]
@SteveL-MSFT I'm not able to reproduce the original problem with `iex` and PS7.5 on my mac (and my original c# only repro is now also _not_ failing). Some aspect of this issue _might_ have been addressed in dotnet9 - would you give it a try again?

FWIW, `bash -ic 'date'` is still problematic (although `bash -c 'date' is fine, as is `bash -i`). Something about forced interactive mode `-i` in combination with `-c` still seems to give PS heartburn, though.

**Comment by darthwalsh** [comment]
One other wrinkle I ran into trying to reproduce, if you run a `zsh` shell first, you see that `zsh: suspended (tty output)  pwsh` and you can resume and use pwsh normally:

```
$ zsh
walshca@ADSKKHQYC7QDK4 ~ % bash -i something
bash: something: No such file or directory
walshca@ADSKKHQYC7QDK4 ~ %
walshca@ADSKKHQYC7QDK4 ~ % pwsh
PowerShell 7.5.0
$ bash -i something
bash: something: No such file or directory
zsh: suspended (tty output)  pwsh
walshca@ADSKKHQYC7QDK4 ~ % fg
[1]  + continued  pwsh
NativeCommandExitException: Program "bash" ended with non-zero exit code: 127.
127 ~
$ bash -ic 'date'
Sat Apr 26 05:32:28 PDT 2025
zsh: suspended (tty output)  pwsh
walshca@ADSKKHQYC7QDK4 ~ % fg
[1]  + continued  pwsh
 ~
```

But using Terminal.app I see the pwsh process still crashes when run outside any UNIX shell:
```
$ bash -ic date
Sat Apr 26 05:40:31 PDT 2025
^[[15;1RProcess terminated. Input/output error
   at System.Environment.FailFast(System.Runtime.CompilerServices.StackCrawlMarkHandle, System.String, System.Runtime.CompilerServices.ObjectHandleOnStack, System.String)
```

---

The behavior now is not what I expect from a typical UNIX shell, but maybe the issue is in my expectation

> these are really signals for job control environments which PS is _not_

I wasn't aware of this limitation, that pwsh is the wrong tool if you are doing anything with UNIX job control? Maybe we could document the current behavior at https://learn.microsoft.com/en-us/powershell and close the issue.

**Comment by SchrodingerZhu** [comment]
I think this is not addressed yet.

**Comment by darthwalsh** [comment]
I came across another bizarre issue that might have the same root cause: not handling `SIGTTOU` then the `pwsh` process terminates (unless it is run inside of a different UNIX shell).

1. A subprocess (e.g. `bash`) takes terminal/tty control
2. That subprocess terminates abnormally (`SIGKILL`, force quit, trying to use `/dev/tcp/`, etc.)
3. PowerShell tries to use terminal functions without checking/recovering terminal state

```plaintext
$ zsh
walshca@ADSKKHQYC7QDK4 bin % pwsh
PowerShell 7.5.1
$ bash
bash-3.2$ kill -KILL $$
zsh: suspended (tty output)  pwsh
walshca@ADSKKHQYC7QDK4 bin % fg
[1]  + continued  pwsh
NativeCommandExitException: Program "bash" ended with non-zero exit code: 137.
$ 
```

(I hit this originally trying to use bash to run `exec 3<>/dev/tcp/httpbin.org/80` but didn't know that it would destroy my `pwsh` terminal :( )

**Comment by SchrodingerZhu** [comment]
@JamesWTruher I am on FreeBSD now and cannot do the confirmation. Feel free to close this.

**Comment by LookoutHill** [comment]
I'm on NixOS 25.11 (on x86_64-linux) using PowerShell 7.6.1 and this bug is still very much active. I discovered it by running a VM in cloud-hypervisor but I can trigger it simply with `zsh -ic 'date'`. Wrapping the command with `rlwrap` (e.g. `rlwrap zsh -ic 'date'`) is a workaround.
