### ISSUE TITLE
Invisible symbol: paste "€" in PowerShell 7.2.0-preview.5

### ISSUE THREAD

**Issue by zongwan** [PowerShell/PowerShell#15418]
## Steps to reproduce
copy to clipboard
`"item=1000€"`

✔paste in Windows PowerShell
`PS C:\Users\jeffery> "item=1000€"`

❌paste in PowerShell 7.2.0-preview.5
`PS C:\Users\jeffery> "item=1000"`

## Expected behavior && Actual behavior
![image](https://user-images.githubusercontent.com/1185694/118576551-54898c80-b7bb-11eb-82af-af185cc3a437.png)

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.2.0-preview.5
PSEdition                      Core
GitCommitId                    7.2.0-preview.5
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

```none
Name                           Value
----                           -----
PSVersion                      5.1.19041.906
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.906
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by jborean93** [comment]
What's the result when you run the following in both WinPS and PS?

```powershell
[Console]::InputEncoding
[Console]::OutputEncoding
```

**Comment by zongwan** [comment]
> What's the result when you run the following in both WinPS and PS?
> 
> ```powershell
> [Console]::InputEncoding
> [Console]::OutputEncoding
> ```

```
PS C:\Users\hou> [Console]::InputEncoding


BodyName          : gb2312
EncodingName      : 简体中文(GB2312)
HeaderName        : gb2312
WebName           : gb2312
WindowsCodePage   : 936
IsBrowserDisplay  : True
IsBrowserSave     : True
IsMailNewsDisplay : True
IsMailNewsSave    : True
IsSingleByte      : False
EncoderFallback   : System.Text.InternalEncoderBestFitFallback
DecoderFallback   : System.Text.InternalDecoderBestFitFallback
IsReadOnly        : True
CodePage          : 936



PS C:\Users\hou> [Console]::OutputEncoding


BodyName          : gb2312
EncodingName      : 简体中文(GB2312)
HeaderName        : gb2312
WebName           : gb2312
WindowsCodePage   : 936
IsBrowserDisplay  : True
IsBrowserSave     : True
IsMailNewsDisplay : True
IsMailNewsSave    : True
IsSingleByte      : False
EncoderFallback   : System.Text.InternalEncoderBestFitFallback
DecoderFallback   : System.Text.InternalDecoderBestFitFallback
IsReadOnly        : True
CodePage          : 936
```

```
PowerShell 7.2.0-preview.5
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS C:\Users\hou> [Console]::InputEncoding

EncodingName      : Chinese Simplified (GB2312)
WebName           : gb2312
HeaderName        : gb2312
BodyName          : gb2312
Preamble          :
WindowsCodePage   :
IsBrowserDisplay  :
IsBrowserSave     :
IsMailNewsDisplay :
IsMailNewsSave    :
IsSingleByte      : False
EncoderFallback   : System.Text.InternalEncoderBestFitFallback
DecoderFallback   : System.Text.InternalDecoderBestFitFallback
IsReadOnly        : True
CodePage          : 936


PS C:\Users\hou> [Console]::OutputEncoding

EncodingName      : Chinese Simplified (GB2312)
WebName           : gb2312
HeaderName        : gb2312
BodyName          : gb2312
Preamble          :
WindowsCodePage   :
IsBrowserDisplay  :
IsBrowserSave     :
IsMailNewsDisplay :
IsMailNewsSave    :
IsSingleByte      : False
EncoderFallback   : System.Text.InternalEncoderBestFitFallback
DecoderFallback   : System.Text.InternalDecoderBestFitFallback
IsReadOnly        : False
CodePage          : 936
```

**Comment by zongwan** [comment]
set encoding, but `€` is still invisible.
```
[console]::InputEncoding = [console]::OutputEncoding = [System.Text.Encoding]::UTF8
```

**Comment by kasini3000** [comment]
This problem can be reproduced, including win terminal. But there is no problem in the script.

**Comment by daxian-dbw** [comment]
@zongwan Did you try pasting with <kbd>Ctrl+v</kbd>? It's a known issue with `right click` pasting, but <kbd>Ctrl+v</kbd> should work fine.

**Comment by zongwan** [comment]
> @zongwan Did you try pasting with Ctrl+v? It's a known issue with `right click` pasting, but Ctrl+v should work fine.

Yes, get the same result.

**Comment by zongwan** [comment]
It works fine when I checkmark **“Use legacy console (requires relaunch)”**. (7.2.0-preview.5) 
But many scripts don't work properly in legacy console mode.

**Comment by 4lex11s** [comment]
Hello, 
I have the same behavior with the character **·** ([Interpunct](https://en.wikipedia.org/wiki/Interpunct), accessible with <kbd>ALT</kbd> + <kbd>0183 </kbd>)

Even with:
```powershell
[console]::InputEncoding = [console]::OutputEncoding = [System.Text.Encoding]::UTF8
```
## My configuration 
```powershell
 [Console]::InputEncoding

    IsSingleByte      : True
    EncodingName      : Western European (DOS)
    WebName           : ibm850
    HeaderName        : ibm850
    BodyName          : ibm850
    Preamble          :
    WindowsCodePage   :
    IsBrowserDisplay  :
    IsBrowserSave     :
    IsMailNewsDisplay :
    IsMailNewsSave    :
    EncoderFallback   : System.Text.InternalEncoderBestFitFallback
    DecoderFallback   : System.Text.InternalDecoderBestFitFallback
    IsReadOnly        : True
    CodePage          : 850


[Console]::OutputEncoding

    IsSingleByte      : True
    EncodingName      : Western European (DOS)
    WebName           : ibm850
    HeaderName        : ibm850
    BodyName          : ibm850
    Preamble          :
    WindowsCodePage   :
    IsBrowserDisplay  :
    IsBrowserSave     :
    IsMailNewsDisplay :
    IsMailNewsSave    :
    EncoderFallback   : System.Text.InternalEncoderBestFitFallback
    DecoderFallback   : System.Text.InternalDecoderBestFitFallback
    IsReadOnly        : False
    CodePage          : 850
```

## Step to reproduce
```Powershell
# copy from visual code or Notepad++ in UTF-8 or from github
$dst='OU=02-grpes_d·utilisateurs,OU=02-Groupes,DC=example,DC=com'
# result in pwsh after pasting.
$dst='OU=02-grpes_dutilisateurs,OU=02-Groupes,DC=example,DC=com'
```

## Nota bene
The interpoint is very useful to replace the single quote, it does not pose any problem on the command line ...

**Comment by StevenBucher98** [comment]
Is this still an issue for you on the latest stable release of PowerShell 7.2? @zongwan

**Comment by Tyriar** [comment]
@StevenBucher98 I can reproduce the problem in pwsh 7.2.4.

The difference in right click and ctrl+v in VS Code is explained because we have this keybinding built-in:

```json
   { "key": "ctrl+v",                "command": "workbench.action.terminal.sendSequence",
                                     "when": "terminalFocus && !accessibilityModeEnabled && terminalShellType == 'pwsh'",
                                     "args": {"text":"\u0016"} },
```

This allows PSReadLine to handle pasting which does a better job with multi-line strings. Right click just does a regular paste and I don't think we should fix this to have a similar send a sequence to PSReadLine on click until custom mouse bindings are implemented (https://github.com/microsoft/vscode/issues/3130).

So the problem here is pwsh for some reason filters out the `€` character, the fact that it works fine in cmd.exe means this is a problem in pwsh.

**Comment by vadhbka** [comment]
I'm having the same problem.
"◆◇□■▲△▼▽"
When I right click and paste a string containing these characters, it disappears

Name                           Value
----                           -----
PSVersion                      7.3.3
PSEdition                      Core
GitCommitId                    7.3.3
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by StevenBucher98** [comment]
I am able to copy that string no problem @vadhbka, what version of PSReadLine are you using?

**Comment by daxian-dbw** [comment]
As I read through the comments, it seems this is still an issue that only reproduces with mouse right clicking, not with the <kbd>Ctrl+v</kbd> key-binding. If so, then this is due to the .NET issue https://github.com/dotnet/runtime/issues/38966.

There are quite a few duplicate issues in PSReadLine/PowerShell repos due to the same .NET issue:
- https://github.com/PowerShell/PSReadLine/issues/1603
- https://github.com/PowerShell/PowerShell/issues/13102
- https://github.com/PowerShell/PSReadLine/issues/760
- https://github.com/PowerShell/PowerShell/issues/12963

**Comment by vadhbka** [comment]
@StevenBucher98
PSReadLine version is 2.2.6

@daxian-dbw
Thanks for all the info
It will be helpful!

I also tried it in different environments
Windows: 10,11
OS Language: en-US, ja-JP
InputEncoding: 437, 932
OutputEncoding: 437, 932
run PowerShell by: console, Terminal in Visual Studio Code 
The problem reproduced regardless of these

However, I have confirmed that only the Windows Terminal can be pasted correctly on both Windows 10 and 11.
(I see from other issues that some people are reproducing the problem with Windows Terminal)

**Comment by daxian-dbw** [comment]
> (I see from other issues that some people are reproducing the problem with Windows Terminal)

Something must be fixed in Windows Terminal now. When I reported https://github.com/dotnet/runtime/issues/38966, it happened in Windows Terminal. But it's been almost 3 years since then, so I don't know for sure if that still holds.

For the repros from the initial PR description and https://github.com/PowerShell/PowerShell/issues/15418#issuecomment-1453201899, they work fine for me in Windows Terminal (both right-clicking and `ctrl+v`) in PowerShell, but in `conhost`, only `ctrl+v` works, not the `right-clicking`.
