### ISSUE TITLE
Unexpected installer error code 2502 and 2503

### ISSUE THREAD

**Issue by GauravSahare27** [PowerShell/PowerShell#15439]
I recently fresh installed Windows 10 21H1 (Build 19043.928) 64 bit. I am trying to install PowerShell v7.1.3.msi stable 64 bit, but unexpected error code 2502 and 2503 are showing. But PowerShell was installed are worked well in previous builds. 1st I thought that the application that already saved might be corrupted, so I again downloaded PowerShell, and trying to install, also I performed "troubleshoot compatibility" but problem is still present.
![Screenshot (1)](https://user-images.githubusercontent.com/39850181/119233594-7bdbb300-bb47-11eb-80b8-3fdd63e0de66.png)
![Screenshot (2)](https://user-images.githubusercontent.com/39850181/119233601-8302c100-bb47-11eb-95da-ac307f35819e.png)

**Comment by iSazonov** [comment]
@GauravSahare27 Where did you download the msi from? Could you please re-download and confirm that the msi is not damaged?

**Comment by JAK1047** [comment]
I've only seen those particular error codes with permission issues. Usually a lack of write access to C:\Windows\Temp or rarely permission issues on msiexec.exe itself. (Used to have a batch script at my company we pushed to win7 workstations to unreg\reg msiexec to fix these exact errors)

Just for the sake of crossing it of the list are you running the install as admin?

**Comment by GauravSahare27** [comment]
> I've only seen those particular error codes with permission issues. Usually a lack of write access to C:\Windows\Temp or rarely permission issues on msiexec.exe itself. (Used to have a batch script at my company we pushed to win7 workstations to unreg\reg msiexec to fix these exact errors)
> 
> Just for the sake of crossing it of the list are you running the install as admin?

Yes, you are right, it's a known issue and I got solution from Microsoft site. Permission related issue in Windows "Temp" folder, here is a fix that I want to share:

1. Go to directory "C:\Windows" and right click on "Temp" folder and select "Properties".
2. In "Security" tab, select "Advanced" then select "Add" (if "Change Permission" option showing, then select this and then select "Add").
3. Now select "select a principal", type any word or name and select "check names" and click OK.
4. In "Basic Permissions" , tick/check "Full Control" and select "OK".
5. Repeat the same process with built-in "Administrators" permission which is already showing in permission entry.
6. Now select "Apply > OK" , if any warning message showing related from security, then accept this setting.
7. Now in "Security" tab, select "Edit" option, select the permission you created in step 3 and check "Full Control" and click "Apply".
8. Now select "Administrators" permission, check "Full Control" and click "Apply > OK".

This step does not affact security, but a fix of error 2502 and 2503.

**Comment by zetmanutentez** [comment]
Como administrador abra o PowerShell e cole o seguinte comando e "enter":
iex "& { $(irm https://aka.ms/install-powershell.ps1) } -UseMSI"
Pronto. Simples assim

**Comment by srinivas330** [comment]
tried toomany attempts , and diffrent ways but still facing same isssue Installer has encountered an unexpected error 2503 fix -How to fix error code 2503 and 2502

**Comment by Attilio49** [comment]
> tried toomany attempts , and diffrent ways but still facing same isssue Installer has encountered an unexpected error 2503 fix -How to fix error code 2503 and 2502

I've overcome the errors 2502 - 2503, encountered with a lot of files  .MSI (including PowerShell-7.4.6-win-x64.msi), simply converting them to .EXE: then, just launch the installation "AS ADMINISTRATOR" et voilà... the game is done.
(I use the free tool "MSI to EXE Converter.exe", but there are others, and the process is almost instantaneous).
