### ISSUE TITLE
update-help fails for 'ConfigDefenderPerformance, PSReadline'    -UICulture en-US.

### ISSUE THREAD

**Issue by bobknowscode** [PowerShell/PowerShell#17067]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

When running update-help the following errors are seen...
PS C:\Windows\System32> update-help -force                                                                              _Update-Help: Failed to update Help for the module(s) 'ConfigDefenderPerformance, PSReadline' with UI culture(s) {en-US} : One or more errors occurred. (Response status code does not indicate success: 404 (The specified blob does not exist.).).
English-US help content is available and can be installed using: Update-Help -UICulture en-US._

running the recommended command produces the same issue
PS C:\Windows\System32> update-help  -UICulture en-US
Update-Help: Failed to update Help for the module(s) 'ConfigDefenderPerformance, PSReadline' with UI culture(s) {en-US} : One or more errors occurred. (Response status code does not indicate success: 404 (The specified blob does not exist.).).
English-US help content is available and can be installed using: Update-Help -UICulture en-US.

### Expected behavior

```console
The update-help should not be showing these errors; 
All the error text (mine is red) leads me to believe update-help as an operation has failed .   

Why does the server respond with 404? Where did the help blob go?
```

### Actual behavior

```console
PS C:\Windows\System32> update-help
Update-Help: Failed to update Help for the module(s) 'ConfigDefenderPerformance, PSReadline' with UI culture(s) {en-US} : One or more errors occurred. (Response status code does not indicate success: 404 (The specified blob does not exist.).).
```

### Error details

```console
PS C:\Windows\System32> Get-Error

Exception             :
    Type    : System.Exception
    Message : Failed to update Help for the module(s) 'ConfigDefenderPerformance, PSReadline' with UI culture(s)
{en-US} : One or more errors occurred. (Response status code does not indicate success: 404 (The specified blob does
not exist.).).
              English-US help content is available and can be installed using: Update-Help -UICulture en-US.
    HResult : -2146233088
CategoryInfo          : InvalidOperation: (:) [Update-Help], Exception
FullyQualifiedErrorId : UnknownErrorId,Microsoft.PowerShell.Commands.UpdateHelpCommand
InvocationInfo        :
    MyCommand        : Update-Help
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 10
    Line             : update-help  -UICulture en-US
    PositionMessage  : At line:1 char:1
                       + update-help  -UICulture en-US
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : update-help
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :
```

### Environment data

```powershell
PS C:\Windows\System32> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.5
PSEdition                      Core
GitCommitId                    7.1.5
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


PS C:\Windows\System32> Get-Host

Name             : ConsoleHost
Version          : 7.1.5
InstanceId       : 846ec299-7473-4bfc-a77d-c75aea9c9931
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-US
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace
```

### Visuals

![image](https://user-images.githubusercontent.com/92458643/160138190-08679715-4b70-46ba-95ed-ea426e8afcf5.png)

**Comment by jhoneill** [comment]
**PSReadline** Ships with PowerShell itself and really should be tidied up. It has it's own repo and it might be good to cross post there.

Config Defender Performance is delivered as a part of Windows and depending on OS version the list of modules missing help will vary.  My Windows 11 machine lists ConfigDefenderPerformance, Dism, Get-NetView, Kds, NetQos, PcsvDevice, PKI, Whea and WindowsUpdate as missing in 7.2.2 and  5.1 adds  ConfigDefender, HostNetworkingService,  StorageBusCache, VMDirectStorage  - which I'm assuming PowerShell 7 won't load.  For a few that I've checked, the stub help that is present has a link to the web page with the help so it has been *written*, it just can't be downloaded locally. 

Sadly this has been the case for a long time, and the chances of the PowerShell team getting the various Microsoft teams who deliver modules to do their jobs properly were never good, and seem to have grown worse.

**Comment by Knele83** [comment]
PS C:\Windows\System32> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.5
PSEdition                      Core
GitCommitId                    7.1.5
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


PS C:\Windows\System32> Get-Host

Name             : ConsoleHost
Version          : 7.1.5
InstanceId       : 846ec299-7473-4bfc-a77d-c75aea9c9931
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-US
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace

**Comment by bobknowscode** [comment]
Thank you for looking at this issue.   It seems that it is caused by required files available for download; however, the update worked overall.

Would it be possible to catch such 404 download errors and print a warning instead?  I would assume this will be written in the user's WarningForegroundColor  : Yellow and/or WarningBackgroundColor  : Black

**_Warning_**: Failed to update Help for the module(s) 'ConfigDefenderPerformance, PSReadline' with UI culture(s)
{en-US} : One or more errors occurred. (Response status code does not indicate success: 404 (The specified blob does not exist.).).

This last line  leads the user to think the download file is available; when in fact its not.  Is this last line meaningful?  
              **_English-US help content is available and can be installed using: Update-Help -UICulture en-US._**

**Comment by StevenBucher98** [comment]
I do suggest opening up an issue in the [PSReadLine repo](https://github.com/PowerShell/PSReadLine/issues) as that we can definitely fix. Marking as enhancement for the suggestion for catching the 404 error.

**Comment by bobknowscode** [comment]
I added the improvement here... https://github.com/PowerShell/PSReadLine/issues/3317   Thanks for taking the time to look at this issue.

**Comment by daxian-dbw** [comment]
Just FYI, the issue about `Update-Help PSReadLine` is a known issue due to the in-box PSReadLine module folder name, which has been fixed in newer versions of Windows. Please see this blog for workarounds: https://devblogs.microsoft.com/powershell/updating-help-for-the-psreadline-module/

**Comment by MattBDev** [comment]
Does anyone know why "ConfigDefenderPerformance, Dism, Get-NetView, Kds, NetQos, PcsvDevice, PKI, Whea, WindowsUpdate" might fail with a 404?

**Comment by ehmiiz** [comment]
> Does anyone know why "ConfigDefenderPerformance, Dism, Get-NetView, Kds, NetQos, PcsvDevice, PKI, Whea, WindowsUpdate" might fail with a 404?

They fail because what is displayed and stored in your module path is actually folders incorrect names in terms of case-sensitivty:
PKI should be pki
Dism should be DISM
ConfigDefenderPerformance should be (even more strange) WindowsDefender
Kds should be KDS

and so on, a work-around is to rename them or remove them and update them with their newer version it seems - issue is tracked here:
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/2247

**Comment by sql-sith** [comment]
> Just FYI, the issue about `Update-Help PSReadLine` is a known issue due to the in-box PSReadLine module folder name, which has been fixed in newer versions of Windows. Please see this blog for workarounds: https://devblogs.microsoft.com/powershell/updating-help-for-the-psreadline-module/

For what it's worth, I have a new work laptop and a new personal laptop and both still have problems updating PowerShell help for several modules, including PSReadLine/PSReadline. The "out-of-box experience" has not changed at all from what I can tell.

The personal laptop is running Windows 11 21H2 (OS Build 22000.739) and still has this problem. The work laptop is running a slightly older build at Windows 10 21H2 (OS Build 19044.1706). So while I'm glad people are paying attention to this (quite old) problem, it's really not solved in a way that works for end-users on a fresh install. These are the modules that will not update help on pwsh 7.2.5 on my Windows 11 laptop.

```
Get-Module -ListAvailable `
>>     Dism,
>>     Get-NetView,
>>     Kds,
>>     NetQos,
>>     PcsvDevice,
>>     PKI,
>>     PSReadLine,
>>     Whea,
>>     WindowsUpdate | Select Name, Version

Name          Version
----          -------
PSReadLine    2.1.0
PSReadline    2.0.0
Dism          3.0
Get-NetView   2021.3.23.142
Kds           1.0.0.0
NetQos        2.0.0.0
PcsvDevice    1.0.0.0
PKI           1.0.0.0
Whea          2.0.0.0
WindowsUpdate 1.0.0.0
```

**Comment by hl2guide** [comment]
Please fix this up for British English.

After running: `Update-Help`

I get:

```
Update-Help: Failed to update Help for the module(s) 'ConfigDefenderPerformance, Dism,
Get-NetView, Kds, NetQos, PcsvDevice, PKI, PSReadline, Whea,
WindowsUpdate'
with UI culture(s) {en-GB} : One or more errors occurred. (Response status code does not indicate success: 404 (The specified blob does not exist.).).
English-US help content is available and can be installed using: Update-Help -UICulture en-US.
```

**Comment by ehmiiz** [comment]
This was talked about in the PS Commuinity Call - July 21st 2022:
https://www.youtube.com/watch?v=GcPTjtybohM&t=2281s

**Comment by meyerovb** [comment]
Y'all are confusing the hell outta me, I renamed PSReadline to PSReadLine, had to uninstall and then reinstall PS cause it wouldn't just upgrade after I did that, and now I'm STILL getting 
`Update-Help: Failed to update Help for the module(s) 'ConfigDefenderPerformance' with UI culture(s) {en-US} : One or more errors occurred. (Response status code does not indicate success: 404 (Not Found).).
English-US help content is available and can be installed using: Update-Help -UICulture en-US.`
Should I just live with this or is there some way to fix it.  I don't even need the help... I just wanted to know the command to run to upgrade powershell from within powershell... then I went down this fn rabbit hole

**Comment by cleonard-godaddy** [comment]
Hi @meyerovb! This issue is not about how to upgrade Powershell. There are several ways to do that, but none of them require running `Update-Help` or doing anything else we are talking about here. One way to upgrade PowerShell from a CLI is to use `winget`. However, this assumes you are on Windows, and you may need to install it first. Additionally, there are other things to keep in mind if you are scripting an upgrade - for example, the installer will need to close all your existing PS sessions (including the one that launched `winget`) or it will require a reboot when you're done.

If you do have `winget` and just want to perform the easiest upgrade possible, I'd recommend starting a `cmd` prompt (not PowerShell) and running `winget install --id Microsoft.PowerShell --source winget --exact --interactive`. Using `cmd` simplifies things because if you run `winget` (or any PowerShell installer) from inside PowerShell, then that PowerShell session will have to be shut down during the installation process. You can avoid this by using a different shell, like `cmd`.

If your needs go beyond that, please start another issue in this repo to discuss exactly what you need to do.

**Comment by jhoneill** [comment]
@meyerovb  

The module `ConfigDefenderPerformance` is included with Windows PowerShell , not bundled with PowerShell 7 
If you do `get-module -list ConfigDefenderPerformance | fl *`
You'll see the path to module is under  `C:\Windows\system32\WindowsPowerShell\v1.0\Modules\`  
and help info URI for the module is http://go.microsoft.com/fwlink/?linkid=390762  but if you go to that link it returns a 404 error.  When update help tries to find the help files it gets the same 404 error and that is what you are seeing. 

Some other modules bundled with Windows do the same (I listed ones I know about above).  The way to raise problems with these is via the Windows 10/11 feedback hub but that is slow to get any response, and the PowerShell team should report these ti the team which contributes the module to Windows - @daxian-dbw I think you have reported _some_  has anyone done the exercise of adding all Windows components, and running `update-help` from PowerShell 7,  and logging bugs with other MSFT teams whose components don't download help successfully ? It's a really boring job but it would do a lot for the perception of quality.

**Comment by theJasonHelmick** [comment]
Linking similar issue: https://github.com/PowerShell/PowerShell/issues/13591

**Comment by theJasonHelmick** [comment]
I'm investigating ways to improve the situation with Update-Help, so let me ask here: what if there was a way you could easily configure a 'block' list to prevent retrying an update for missing modules. The error messages would remain the same. This configurable list may initially ship with the modules that we know will not be updated in the future. You can add additional modules if that is needed. Would that be helpful?

**Comment by meyerovb** [comment]
why not just make these warnings?

**Comment by cleonard-godaddy** [comment]
That would be helpful. However, my opinion is that it's more important to get the help that is available instead of allowing me to hide legitimate messages telling me that I've failed to update help. Examples of this are the messages returned when attempting to update PSRead(L|l)ine. 

To be more specific, in addition to giving options to squelch errors, I think it would be good to add more little intelligence to how potential upgrade modules are matched. Let me explain a proposal as a starting point for discussion.

Suppose that there is a signed module from author X called Abc, with version 1, and another signed module, also from author X, called ABC, with version 2. In this case, if you ask PowerShell to find modules named `abc`, it will tell you about both of these versions, even though `abc` does not match the case of either release. Using everyone's favorite example, PSRead(L|l)ine, I can search for `psreadline` in lower case and get back matches that are not lowercase, even in Linux:
```
Get-Module -Name PSReadLine -ListAvailable -All | Select-Object -Property Name, Version | Where-Object Version -ne "0.0"

Name       Version
----       -------
PSReadLine 2.1.0
PSReadline 2.0.0
```
It is an inconsistent user experience to have this consistently case-insensitive policy changed when we run `Update-Help`. 

So I think that the best solution has two parts:

1. Make `Update-Help` case-insensitive with respect to module names, so that `PSReadline` matches `PSReadLine`, as it should in the context of the PowerShell user experience; and
2. Also implement a block list, and repopulate it with modules and versions that the PowerShell team knows to be "terminal," meaning that they do not , and will not/cannot work with `Update-Help`. 

The end state would be that if I have help installed for `PSReadline 2.0.0` and there is help available for `PSReadLine 2.1.0`, running `Update-Help -Module PSReadLine` should succeed (no matter how the user capitalizes `PSReadLine`) and there should be a list of known "offenders" that `Update-Help` will not generate errors for if they fail to process successfully, with users able to append to that list.

**Comment by theJasonHelmick** [comment]
@cleonard-godaddy - Thank you for the additional suggestions.  W are investigating how best to fix update-help, and handling case is part of that investigation along with the block list.

**Comment by cleonard-godaddy** [comment]
@theJasonHelmick - thanks for the update, and thanks for giving us an unofficial mini-update. It is always encouraging to hear from the project team responsible for an issue!

**Comment by jhoneill** [comment]
@theJasonHelmick  Some sort of block list would provide relief from the symptoms 

However the right fix is that any module which ships as part of Windows, but not from the PowerShell team gets its house in order and not ship with a broken link.  Having one part of Microsoft shipping things to hide other parts' bugs is masking the problem not fixing it.  If we use  `ConfigDefenderPerformance`  as an example: it has a link, http://go.microsoft.com/fwlink/?linkid=390762 which gives a 404 error.  Either whoever owns that link needs to figure out why it isn't going to the right place and fixes it  OR the owners `ConfigDefenderPerformance`  need to add something to the next cumulative windows update to move from 1.0 to 1.0.1 and have different, working link . I'm hoping someone from the PowerShell team has filed bugs internally for all the modules known to have broken help links.  

Masking it while that happens is good (and addresses modules - MSFT or otherwise - which won't ever get updated) but the masking process needs to handle the link being fixed or a new version being made available.

**Comment by meyerovb** [comment]
Yeah I get that. Trying to figure out how to do that I ended up trying
help. Which told me I should run update-help. Which led me to this ticket.
So again, other than renaming that folder, what else should I do to fix
update-help? Which I really don’t need to use but am irritated that I can’t
just because.

-- 
Bryan Meyerovich

**Comment by yturbi** [comment]
Try Update-Help -Force -ErrorAction SilentlyContinue

For PSReadline module you need to rename PSReadline to PSReadLine in "C:\Program Files\WindowsPowerShell\Modules" and reload module PSReadLine in PowerShell

**Comment by aitaix** [comment]
> Try `Update-Help -Force -ErrorAction SilentlyContinue`


This worked for me

**Comment by no-identd** [comment]
@yturbi iirc that may end up breaking DISM / CBS / sfc state, but I might confabulate it with a separate issue

**Comment by no-identd** [comment]
And also iirc, that represents part of the reason for the issue with remediating that, because one'd end up having to deploy an INCREDIBLY strange and likely absurdly error prone Windows Update due to bootstrapping issues @jhoneill

(gets even worse once you start thinking about stuff like /resetbase & CompactOS)

**Comment by no-identd** [comment]
See also #13591, via #2247 (thanks, @ehmiiz )

**Comment by 62f** [comment]
> Update-Help -Force -ErrorAction SilentlyContinue
Not I said the ISE:
```
What if: Performing the operation "Update-Help" on target "Microsoft.PowerShell.
Core, Current Version: 5.2.0.0, Available Version: 5.2.0.0, UICulture: en-US".
Update-Help : Failed to update Help for the module(s) 'ConfigDefender, 
ConfigDefenderPerformance, HostNetworkingService, PSReadline' with UI 
culture(s) {en-US} : Unable to retrieve the HelpInfo XML file for UI culture 
en-US. Make sure the HelpInfoUri property in the module manifest is valid or 
check your network connection and then try the command again.
At line:1 char:1
+ Update-Help -Confirm -Force -WhatIf
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [Update-Help], Exceptio 
   n
    + FullyQualifiedErrorId : UnableToRetrieveHelpInfoXml,Microsoft.PowerShell 
   .Commands.UpdateHelpCommand```
   The fact if I am able to post this message should serve as enough "check-network connection".

**Comment by mcdonaldjc** [comment]
This issue occurs for me as well and has on every version of PowerShell I've used. It seems to me that the solution to appease users is rather simple:

1. If a module fails to update, continue silently.

I honestly don't care much if a module fails to update. I just want to know the help that COULD be updated HAS been updated. The rest falls on the developers for these modules.

2. There is no reason to tell me I can run `Update-Help -UICulture en-US` when that is the _exact_ command I just ran.

At the very least, detect what command I used, and skip this part if they match up.

Here's my output from 7.3.6 (x64) on Windows 11.

```
PS> Update-Help -UICulture en-US

Update-Help: Failed to update Help for the module(s) 'ConfigDefenderPerformance, DefenderPerformance, Dism, Get-NetView, Kds, LAPS, NetQos, PcsvDevice, Pester, PKI, Whea, WindowsUpdate' with UI culture(s) {en-US} : One or more errors occurred. (Response status code does not indicate success: 404 (The specified blob does not exist.).).
English-US help content is available and can be installed using: Update-Help -UICulture en-US.
```

Here's some additional information in case it is useful.

```
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.6
PSEdition                      Core
GitCommitId                    7.3.6
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by 62f** [comment]
> This issue occurs for me as well and has on every version of PowerShell I've used. 
the underlying fact for me is that there were no developers left to do any updates because evidently the PS module which could not be updated had been completely and utterly abandoned.

**Comment by nannerpusser** [comment]
> > This issue occurs for me as well and has on every version of PowerShell I've used.
> > the underlying fact for me is that there were no developers left to do any updates because evidently the PS module which could not be updated had been completely and utterly abandoned.

This is the correct answer, if I remember right. The dumb part is that it's just a naming convention issue, essentially. Nothing needs refactored or anything, it just needs a few character replacements and you know, a working end point somewhere that doesn't 404.

**Comment by sdwheeler** [comment]
This is a duplicate of the following issues:

- #13591
- #17067
- #17534
- #17577
- #18064
- #18869

**Comment by theJasonHelmick** [comment]
Duplicate of:
#13591 
#17067
#17534
#17577 
#18064 
#18869

**Comment by eabase** [comment]
Please reopen. Issue persists!

**Comment by eabase** [comment]
@sdwheeler 
Sorry, I completely disagree.  This is a PowerShell issues, as the modules are shipped with it and the OS. It is up to the MS QA team to ensure that you are not shipping modules that can't be updated, and that the PowerShell dev's to report about it to them.

There are likely more than 2 dozen issues here, related to `update-help` failures, all being auto-closed by your silly bot. 
Also, it's too complicated to use the feedback link, and apparently a waste of time since MS already know about this since years.

**Comment by eabase** [comment]
Adding to the list of @ehmiiz  items [here](https://github.com/PowerShell/PowerShell/issues/17067#issuecomment-1158842828). 

Original Directory Names:
```
C:\Program Files\WindowsPowerShell\Modules\Pester\3.4.0
C:\Windows\system32\WindowsPowerShell\v1.0\Modules\ConfigDefenderPerformance
C:\Windows\system32\WindowsPowerShell\v1.0\Modules\DefenderPerformance
C:\Windows\system32\WindowsPowerShell\v1.0\Modules\Dism
C:\Windows\system32\WindowsPowerShell\v1.0\Modules\Get-NetView
C:\Windows\system32\WindowsPowerShell\v1.0\Modules\Kds
C:\Windows\system32\WindowsPowerShell\v1.0\Modules\NetQos
C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PcsvDevice
C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PKI
C:\Windows\system32\WindowsPowerShell\v1.0\Modules\Whea
C:\Windows\system32\WindowsPowerShell\v1.0\Modules\WindowsUpdate
```

We have the new names: 
```
*           Pester
=           ConfigDefenderPerformance
Defender    DefenderPerformance
DISM        Dism
*           Get-NetView
KDS         Kds
NetQoS      NetQos
PCSVDevice  PcsvDevice
pki         PKI
WHEA        Whea
*           WindowsUpdate
      
```

Where **`*`** need special treatment as their correct naming can't be found. 
Also, `Pester` has a [good description of the issue here](https://pester.dev/docs/introduction/installation) (and how to fix it.) 

Most of the correct info I got from looking at this page: 
* https://learn.microsoft.com/en-us/powershell/module/activedirectory/?view=windowsserver2022-ps


Fixing a few of these:
```powershell
Rename-Item -Path "C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PKI" -NewName "pki" -Force
Rename-Item -Path "C:\Windows\system32\WindowsPowerShell\v1.0\Modules\Kds" -NewName "KDS" -Force
Rename-Item -Path "C:\Windows\system32\WindowsPowerShell\v1.0\Modules\Dism" -NewName "DISM" -Force
Rename-Item -Path "C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PcsvDevice" -NewName "PCSVDevice" -Force
Rename-Item -Path "C:\Windows\system32\WindowsPowerShell\v1.0\Modules\NetQos" -NewName "NetQoS" -Force
Rename-Item -Path "C:\Windows\system32\WindowsPowerShell\v1.0\Modules\Whea" -NewName "WHEA" -Force
```

So the reamianing list of items to fix are: 
```
Pester
ConfigDefenderPerformance
DefenderPerformance
Get-NetView
WindowsUpdate
```

Clearly the update function is case sensitive while someone has been using some weird Camel-case during dev...

**Comment by eabase** [comment]
For trouble modules you may want to list them separately: 
```powershell
$m = Get-Module -ListAvailable ConfigDefenderPerformance, DefenderPerformance, DeliveryOptimization, Get-NetView, Pester, WindowsUpdate
$m | select Version, Guid, Name, ProjectUri, HelpInfoUri, ModuleBase | sort Name | ft -AutoSize

# tru to update this list. 
foreach ($i in $m) { Update-Help -UICulture en-US -Module $i  }

```

**Comment by sdwheeler** [comment]
Adding a summary of answers for this issue is being before closing out comments.

The workaround for the **PSReadline** module is documented in the following blog post:

- https://devblogs.microsoft.com/powershell/updating-help-for-the-psreadline-module-in-windows-powershell-5-1/

This other thing to try is to unload the module, then reload it with the properly-cased name. Then update the help.

```powershell
Remove-Module PSReadline
Import-Module PSReadLine
Update-Help PSReadLine -Force
```

The error is expected for the following Windows modules. 

- ConfigDefenderPerformance
- Dism
- Get-NetView
- Kds
- NetQos
- PcsvDevice
- PKI
- StartLayout
- Whea
- WindowsSearch
- WindowsUpdate

The Windows modules are not maintained by the PowerShell team. To prevent the error, the module owners on the Windows team must fix the modules. For modules that ship in Windows, open a support case with Windows Support or send feedback via the Windows Feedback Hub. For more information, see [Send feedback to Microsoft with the Feedback Hub app][1].

[1]: https://support.microsoft.com/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332



<blockquote><div><img src="https://devblogs.microsoft.com/powershell/wp-content/uploads/sites/30/2019/02/Powershell_2561.png" height="14"> PowerShell Team</div><div><strong><a href="https://devblogs.microsoft.com/powershell/updating-help-for-the-psreadline-module/">Page not found - PowerShell Team</a></strong></div></blockquote>
