### ISSUE TITLE
Update-Help fails silently for UICulture en-GB

### ISSUE THREAD

**Issue by dkaszews** [PowerShell/PowerShell#17696]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Help pages for `about_topics` are missing and cannot be downloaded on en-GB locale. Verbose output shows only redirects and zero downloads. Issue can be fixed by passing `-UICulture en-US` to `Update-Help`. I understand that the help pages are set to specific locale, but if it causes them to be completely missing in a different locale of same language, it's a bad user experience. Either show a warning "Help pages for UICulture en-GB not found, but available in en-US, try calling with `-UICulture en-US`", or just download them automatically. `Get-Help` already works with partial locale matches, just `Update-Help` needs fixing. 

```powershell
> Get-UICulture
LCID             Name             DisplayName
----             ----             -----------
2057             en-GB            English (United Kingdom)
> Update-Help -Force -Verbose
```

### Expected behavior

```console
> Get-Help about_operators
ABOUT_OPERATORS
Short description
Describes the operators that are supported by PowerShell.
```

### Actual behavior

```console
> Get-Help about_operators
Get-Help: Get-Help could not find about_operators in a help file in this session. To download updated help topics type: "Update-Help". To get help online, search for the help topic in the TechNet library at https://go.microsoft.com/fwlink/?LinkID=107116.
```

### Error details

```console
> get-error
Exception             :
    Type        : Microsoft.PowerShell.Commands.HelpNotFoundException
    ErrorRecord :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Get-Help could not find about_operators in a help file in this session.
To download updated help topics type: "Update-Help". To get help online, search for the help
topic in the TechNet library at https://go.microsoft.com/fwlink/?LinkID=107116.
            HResult : -2146233087
        CategoryInfo          : ResourceUnavailable: (:) [],
ParentContainsErrorRecordException
        FullyQualifiedErrorId : HelpNotFound
        ErrorDetails          :
    HelpTopic   : about_operators
    Message     : Get-Help could not find about_operators in a help file in this session. To
download updated help topics type: "Update-Help". To get help online, search for the help
topic in the TechNet library at https://go.microsoft.com/fwlink/?LinkID=107116.
    HResult     : -2146233087
CategoryInfo          : ResourceUnavailable: (:) [Get-Help], HelpNotFoundException
FullyQualifiedErrorId : HelpNotFound,Microsoft.PowerShell.Commands.GetHelpCommand
InvocationInfo        :
    MyCommand        : Get-Help
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 8
    Line             : get-help about_operators
    PositionMessage  : At line:1 char:1
                       + get-help about_operators
                       + ~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : get-help
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :
```

### Environment data

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      7.3.0-preview.5
PSEdition                      Core
GitCommitId                    7.3.0-preview.5
OS                             Linux 5.15.0-1011-raspi #13-Ubuntu SMP PREEMPT Thu Jun 2 11:44…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by dkaszews** [comment]
Interestingly, when running Pester tests I notice the following (output slightly messed up by tmux and ssh):

```powershell
  Describing Get-Help should accept arrays as the -Parameter parameter value
    [-] Error occurred in Describe block 0msles - test ? pattern, is pending 0ms
      Exception: Failed to update Help for the module(s) 'Microsoft.PowerShell.Core' with UI cu
lture(s) {en-GB} : Unable to retrieve the HelpInfo XML file for UI culture en-GB. Make sure the
 HelpInfoUri property in the module manifest is valid or check your network connection and then
 try the command again.. for foo ...                                                        ]
      English-US help content is available and can be installed using: Update-Help -UICulture e
n-US.
      at UpdateHelpFromLocalContentPath, /home/dkaszews/code/PowerShell/test/powershell/engine/
Help/HelpSystem.Tests.ps1: line 33
```

So there is some exception with exact hint I suggested, it is just being silenced by `Update-Help`. Will investigate further.

**Comment by dkaszews** [comment]
Another finding: I can get a nice descriptive error if I specify culture explicitly. So fix should be as easy as making sure `Update-Help` with implicit culture works the same as `Update-Help -UICulture (Get-UICulture)`:

```powershell
> Update-Help 'microsoft.powershell.core' -Verbose
VERBOSE: Resolving URI: "https://aka.ms/powershell72-help"
VERBOSE: Your connection has been redirected to the following URI: "https://pshelpprod.blob.core.windows.net/cabinets/powershell-7.2/"
VERBOSE: Resolving URI: "https://aka.ms/powershell72-help"
VERBOSE: Your connection has been redirected to the following URI: "https://pshelpprod.blob.core.windows.net/cabinets/powershell-7.2/"
> Update-Help 'microsoft.powershell.core' -Verbose -UICulture en-gb
VERBOSE: Resolving URI: "https://aka.ms/powershell72-help"
VERBOSE: Your connection has been redirected to the following URI: "https://pshelpprod.blob.core.windows.net/cabinets/powershell-7.2/"
Update-Help: Failed to update Help for the module(s) 'Microsoft.PowerShell.Core' with UI culture(s) {en-GB} : The specified culture is not supported: en-GB. Specify a culture from the following list: {en-US}..
English-US help content is available and can be installed using: Update-Help -UICulture
```

**Comment by sdwheeler** [comment]
This has been asked and answered in other issues. The help system was originally designed to support multiple languages. However, we are only able to publish the updateable help for the `en-US` locale. If your system is not set to use the `en-US` locale then you must specify that locale when running `Update-Help`.

```powershell
Update-Help -UICulture en-US -Force
```

**Comment by dkaszews** [comment]
@sdwheeler Understood, however it is not stated anywhere clearly when not using implicit locale, even when running with `-Verbose`. Command just does nothing silently. It took me more than an hour to find the problem and as I said, it's a bad user experience, especially considering it affects those seeking help already.

Also, is there a reason why `Update-Help -UICulture (Get-UICulture)` throws a nice descriptive error, but `Update-Help` does not? I propose to simply align the two cases. Or, if we don't want to introduce a potentially breaking change (throwing an error where previously no error was thrown, which could mess up scripts with `-ErrorAction Stop`), make it a warning instead.

**Comment by sdwheeler** [comment]
This silent failure is documented in the docs for `Update-Help`.

![image](https://user-images.githubusercontent.com/19415881/180470484-3b125a0f-7af1-4e08-abbd-14f8b13e763b.png)

However, I agree that the silent failure is an issue that should be fixed.

**Comment by daxian-dbw** [comment]
> Also, is there a reason why Update-Help -UICulture (Get-UICulture) throws a nice descriptive error, but Update-Help does not? I propose to simply align the two cases. Or, if we don't want to introduce a potentially breaking change (throwing an error where previously no error was thrown, which could mess up scripts with -ErrorAction Stop), make it a warning instead.

@dkaszews Feel free to open a separate issue about improving this user experience.

**Comment by dkaszews** [comment]
Reopen: not resolved, agreed that fix is necessary.

> Feel free to open a separate issue about improving this user experience.

@daxian-dbw This is the same issue, I was just wondering why explicit culture behaves differently.

I have root-caused the issue, it looks like it it was designed this way, but in my opinion implemented incorrectly. When using implicit culture, it defaults to `Get-UICulture`, but with fallbacks as recursive parents. Parent of `en-GB` is `en`, so it returns `[ "en-GB", "en" ]`. Then when `HelpCultureNotSupported` is thrown in the implicit culture case, the exception is silenced to try and use fallbacks. Problem is that this silencing does not check if there are any more fallbacks, so if neither `en-GB` nor `en` can find help, command fails silently.

I propose a fix to store the first exception of this type, then throw it at the end of the function if none of the languages succeeded. It is easiest, and provides the same descriptive error as when using explicit culture with no help. 

```csharp
// UpdateableHelpCommandBase.cs:511
// `_language` holds `UICulture` because option used to be called `-Language`
// `GetCurrentUICulture()` returns `[ "en-GB", "en" ]`
var cultures = _language ?? _helpSystem.GetCurrentUICulture();

// UpdateableHelpCommandBase.cs:550
catch (UpdatableHelpSystemException e)
{
    if (e.FullyQualifiedErrorId == "HelpCultureNotSupported")
    {
        installed = false;

        if (_language != null)  // DKASZEWS: true for implicit culture
        {
            // Display the error message only if we are not using the fallback chain
            ProcessException(module.ModuleName, culture, e);
        }
    }
    else
    {
        ProcessException(module.ModuleName, culture, e);
    }
}

// UpdateableHelpCommandBase.cs:584
// If -Language is not specified, we only install
// one culture from the fallback chain
if (_language == null && installed)
{
    break;
}
```

**Comment by daxian-dbw** [comment]
@dkaszews Can you submit a PR for the fix?

**Comment by dkaszews** [comment]
Will do. May need help with writing a test for it, but we can discuss it there.

**Comment by sdwheeler** [comment]
PR in progress
