### ISSUE TITLE
Function & Cmdlet Name Tab Completion Broken in the ConfigManager (CMSITE) Provider

### ISSUE THREAD

**Issue by alexlarner** [PowerShell/PowerShell#20803]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

## Summary

7.4.0 seems to have broken cmdlet & function **name** tab completion for **all** cmdlet & functions while the location is set to the Config Manager provider (`CMSITE`). This was working just fine in previous versions of PowerShell 7.

## Scope

- Tab completion for cmdlet & function **parameter** names & values is **not** broken, even when the location is set to the `CMSITE` provider.
- Cmdlet & Function **name** tab completion is **not** broken when the location is set to **any** of the [built-in providers](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_providers?view=powershell-7.4#built-in-providers).
- I can reproduce this on multiple machines.

## Workaround

Reverting back to a previous version of PowerShell, i.e. `7.3.10`, fixes the issue.

## Background Info

My version of the `ConfigurationManager` module shouldn't matter since reverting back to PowerShell 7.3.10 fixes the issue, but just in case I am using version `5.2303.1089.1000` of the module.

## Setup Code

```
PS C:\> Import-Module ConfigurationManager
PS C:\> $SiteCode = Get-PSDrive -PSProvider CMSITE
PS C:\> Set-Location -Path "$($SiteCode.Name):\"
PS DCC:\> Get-Ite{Tab}
PS DCC:\> function Test-TabCompletion {}
PS DCC:\> Test-TabCompletio{Tab}
```

### Expected behavior

```console
PS DCC:\> Get-Item
PS DCC:\> Test-TabCompletion
```

### Actual behavior

```console
PS DCC:\> Get-Ite
PS DCC:\> Test-TabCompletio
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by MartinGC94** [comment]
It's probably related to the change I made here: https://github.com/PowerShell/PowerShell/pull/19489 I don't have any way to test tab completion in that provider though. Can you try to CD into that provider and run this: `TabExpansion2 -inputScript Get-` and post the full error details when it hopefully throws?

**Comment by MartinGC94** [comment]
Okay, it's probably failing here: https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs#L4786 because it's somehow finding 2 items with the same name in a folder/container. Can you run the following from that same location? `ls -LiteralPath .\ | select -ExpandProperty PSPath` and see if the same path shows up twice in the results?  
Also, can you run this: `Get-PSProvider -PSProvider CMSITE | select -ExpandProperty ItemSeparator` and validate that the reported item separator matches the one you see for each item in that list?  
Finally, can you tell me if it includes the provider name in the pspath results from before? Like: `Microsoft.PowerShell.Core\FileSystem::C:\Users\Martin\.dotnet`

**Comment by alexlarner** [comment]
1. `ls -LiteralPath .\ | select -ExpandProperty PSPath` 
    - Returns 21 identical entries of `AdminUI.PS\CMSite::[Config Manager Primary FQDN Redacted]\`
1. `Get-PSProvider -PSProvider CMSITE | select -ExpandProperty ItemSeparator`
    - Returns `\` 
1. Yes `CMSITE` is included in all the PSPath entries above

**Comment by MartinGC94** [comment]
Seems like the SCCM team misunderstood the purpose of the PSPath property in the provider system. The whole idea behind the provider system is that you can refer to objects by a path, similar to what you would do on a filesystem but obviously that can't work if the same path points to 21 different objects.  
It would have been nice if this had been enforced from the start but I guess that ship has sailed so we'll just have to handle their mistake by ignoring duplicates. I'll create a PR to fix this later today.

**Comment by alexlarner** [comment]
Thanks

**Comment by alexlarner** [comment]
> I've created the PR here: #20815 if you have the time feel free to download the Windows build that will get created as part of the automatic tests and then confirm that the changes I made actually fixed the issue for you.

It's fixed now. Thanks!

**Comment by alexlarner** [comment]
> I've created the PR here: #20815 if you have the time feel free to download the Windows build that will get created as part of the automatic tests and then confirm that the changes I made actually fixed the issue for you.

Sorry, for the late response, but that didn't seem to fix it.

And now when I try to run `TabExpansion2 -inputScript Get-`, I get this error instead.

```
ErrorRecord                 : Exception calling "CompleteInput" with "3" argument(s): "StartIndex cannot be less than zero. (Parameter 'startIndex')"
WasThrownFromThrowStatement : False
TargetSite                  : Void ConvertToMethodInvocationException(System.Exception, System.Type, System.String, Int32, System.Reflection.MemberInfo)
Message                     : Exception calling "CompleteInput" with "3" argument(s): "StartIndex cannot be less than zero. (Parameter 'startIndex')"
Data                        : {}
InnerException              : System.ArgumentOutOfRangeException: StartIndex cannot be less than zero. (Parameter 'startIndex')
                                 at System.String.Remove(Int32 startIndex)
                                 at System.Management.Automation.CompletionCompleters.GetDefaultProviderResults(CompletionContext context, ProviderInfo provider, Collection`1 resolvedPaths, String filterText, Boolean containersOnly,
                              Boolean relativePaths, Boolean literalPaths, Boolean inputUsedHome, String providerPrefix, StringConstantType stringType) in
                              D:\a\1\s\src\System.Management.Automation\engine\CommandCompletion\CompletionCompleters.cs:line 4820
                                 at System.Management.Automation.CompletionCompleters.CompleteFilename(CompletionContext context, Boolean containerOnly, HashSet`1 extension) in
                              D:\a\1\s\src\System.Management.Automation\engine\CommandCompletion\CompletionCompleters.cs:line 4560
                                 at System.Management.Automation.CompletionAnalysis.CompleteFileNameAsCommand(CompletionContext completionContext) in
                              D:\a\1\s\src\System.Management.Automation\engine\CommandCompletion\CompletionAnalysis.cs:line 2398
                                 at System.Management.Automation.CompletionAnalysis.GetResultForIdentifier(CompletionContext completionContext, Int32& replacementIndex, Int32& replacementLength) in
                              D:\a\1\s\src\System.Management.Automation\engine\CommandCompletion\CompletionAnalysis.cs:line 2121
                                 at System.Management.Automation.CompletionAnalysis.GetResultHelper(CompletionContext completionContext, Int32& replacementIndex, Int32& replacementLength) in
                              D:\a\1\s\src\System.Management.Automation\engine\CommandCompletion\CompletionAnalysis.cs:line 437
                                 at System.Management.Automation.CompletionAnalysis.GetResults(PowerShell powerShell, Int32& replacementIndex, Int32& replacementLength) in
                              D:\a\1\s\src\System.Management.Automation\engine\CommandCompletion\CompletionAnalysis.cs:line 390
                                 at System.Management.Automation.CommandCompletion.CompleteInputImpl(Ast ast, Token[] tokens, IScriptPosition positionOfCursor, Hashtable options) in
                              D:\a\1\s\src\System.Management.Automation\engine\CommandCompletion\CommandCompletion.cs:line 535
                                 at CallSite.Target(Closure, CallSite, Type, String, Int32, Hashtable)
HelpLink                    :
Source                      : System.Management.Automation
HResult                     : -2146233087
StackTrace                  :    at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Exception exception, Type typeToThrow, String methodName, Int32 numArgs, MemberInfo memberInfo) in
                              D:\a\1\s\src\System.Management.Automation\engine\runtime\Operations\MiscOps.cs:line 2111
                                 at CallSite.Target(Closure, CallSite, Type, String, Int32, Hashtable)
                                 at <ScriptBlock><End>(Closure, FunctionContext)
```

I believe I downloaded the right build. I downloaded [this](https://dev.azure.com/powershell/2972bb5c-f20c-4a60-8bd9-00ffe9987edc/_apis/build/builds/142044/artifacts?artifactName=build&api-version=7.1&%24format=zip).

**Comment by MartinGC94** [comment]
Thanks. I've found a premade SCCM lab by MS that I can download and test this on. Will investigate and try to fix it in the near future.

**Comment by alexlarner** [comment]
> @alexlarner You can download daily build from home page of the repository and if you still see the issue please report in #20803

The repo home page [Windows link](https://powershell.visualstudio.com/PowerShell/_build?definitionId=19&_a=completed) takes you to a `PowerShell-CI-windows` pipeline, however there is also a `PowerShell-CI-Windows-daily` listed under [Pipelines](https://powershell.visualstudio.com/PowerShell/_build). I didn't know which of those you were referring to, so I attempted to test the latest of both.

I was able to download and run [PR-20913-20231212.03](https://powershell.visualstudio.com/PowerShell/_build/results?buildId=142485&view=results) from the `PowerShell-CI-windows` pipeline, and it had the same issue

I couldn't get the latest two [PowerShell-CI-Windows-daily](https://powershell.visualstudio.com/PowerShell/_build?definitionId=32&_a=summary) builds to run as they were blocked from running by our company's Windows security.

**Comment by iambdud** [comment]
I am still having this issue with 7.4.3. Was the change reverted?

**Comment by MartinGC94** [comment]
Looking at the 7.4 release branch, it doesn't seem like the fix has been added there: https://github.com/PowerShell/PowerShell/blob/release/v7.4/src/System.Management.Automation/engine/CommandCompletion/CompletionCompleters.cs#L4858 so I guess they've forgotten to backport it (assuming they will do that since it was a regression).  
Hopefully they'll do that, but if not then I guess you'll just have to use 7.5

**Comment by iambdud** [comment]
Thanks for the reply. I am using 7.5 in the meantime.

Sorry for my ignorance... but where did the fix go if it didn't make it into 7.4?
