### ISSUE TITLE
Debian/Ubuntu at packages.microsoft.com not updated for 7.4.2 release

### ISSUE THREAD

**Issue by J0F3** [PowerShell/PowerShell#21493]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Version 7.4.2 can not be installed installed on Ubuntu 20.04 and 22.04 through the official Microsoft Repo (packages.microsoft.com)

It seems that the deb packages for 7.4.2 are not get pushed to the repo because at https://packages.microsoft.com/ubuntu/20.04/prod/pool/main/p/powershell/ and https://packages.microsoft.com/ubuntu/22.04/prod/pool/main/p/powershell/ is 7.4.1 still the latest version.

It seems also to be the same for Debian packages. 

Please update the repos because this currently prevents users to update to the latest LTS PowerShell version.

Thx!

### Expected behavior

```console
`apt-get update` should update powershell to version 7.4.2
```

### Actual behavior

```console
`apt-get update` finds no update for powershell.
Explicit installation of 7.4.2 with `apt-get install powershell=7.4.2-1.deb` fails because the package can not be found.
```

### Environment data

```powershell
not relevant
```

**Comment by juvtib** [comment]
Hi Jonas, 

I don't have any information about the .DEB. But, I want to add to your issue that the snap is also out-of-date. This is a common issue on Linux. The latest version of PowerShell was released on April 11, but we're still waiting for updates on officially supported platforms. 

Regards, 

``` PowerShell
$PSVersionTable         

Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             openSUSE Tumbleweed
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


snap refresh --list     

All snaps up to date.


snap list powershell    

Name        Version  Rev  Tracking       Publisher              Notes
powershell  7.4.1    264  latest/stable  microsoft-powershell✓  classic

```

See Also 

* [Platform Support - Investments for 2024](https://devblogs.microsoft.com/powershell/powershell-and-openssh-team-investments-for-2024/#platform-support)
* https://github.com/PowerShell/PowerShell/issues/21056#issuecomment-1891308131

**Comment by robamoroso** [comment]
I'd like to add that since the latest version of powershell available in the official apt repo is 7.4.1 it takes a long time to start up because it checks for the new version and displays a message. This happened on a previous update as well and was resolved when the new version was available and the update message wasn't being displayed. Additionally, because powershell takes so long to start due to the update check, it also causes VS Code to fail to load the powershell module because it times out before pwsh finished loading. I'm running Ubuntu 22.04 at present.

**Comment by juvtib** [comment]
> it takes a long time to start up because it checks for the new version and displays a message.

If you'd like, you can add an `export` command to the bottom of ~/.profile and then log back in. 

``` ~/.profile
# PowerShell Update Setting
export POWERSHELL_UPDATECHECK=Off

```

* [about Update Notifications | Microsoft Learn](https://learn.microsoft.com/powershell/module/microsoft.powershell.core/about/about_update_notifications)
* [Skip powershell startup check for new version | Stack Overflow](https://stackoverflow.com/questions/66701954/skip-powershell-startup-check-for-new-version)
* [How do I set environment variables? | Ask Ubuntu](https://askubuntu.com/questions/730/how-do-i-set-environment-variables)

**Comment by matsest** [comment]
Still not updated. As this is an [officially supported installation method](https://learn.microsoft.com/en-us/powershell/scripting/install/install-ubuntu?view=powershell-7.4) it's sad to see that this is not kept updated along with the pwsh releases.

**Comment by EkwzY9PwoKqa7FnPGga6xDigKst3jGmobXnyLAF** [comment]
FWIW, I updated my ansible playbook to use the steps found https://learn.microsoft.com/en-us/powershell/scripting/install/install-ubuntu?view=powershell-7.4#installation-via-direct-download in the sh example, worked fine.

**Comment by Daverd-GM** [comment]
it still isn't in debian12

**Comment by stephannn** [comment]
> it still isn't in debian12

Maybe it is because the file does not exist in the debian 12 folder? Same seems to be the case with Ubuntu 24.04. The file exists in 20.04 and 22.04 but not in 24.04. Not sure if this is related.

**Comment by J0F3** [comment]
That the files do not exist for 24.04 and Debian 12 is the actual problem.

For Debian 12 and Ubuntu 24.04 there area already different issues open: https://github.com/PowerShell/PowerShell/issues/19889
https://github.com/PowerShell/PowerShell/issues/21385

I going to close this because for 22.04 and 20.04 (for which the issue was originally) the package are available now.
