### ISSUE TITLE
Transcription for the host stops, when ANY runspace in the host get closed

### ISSUE THREAD

**Issue by vors** [PowerShell/PowerShell#2334]
## Steps to reproduce

``` powershell
Start-Transcript -Path foo.txt -Force
$rs = [system.management.automation.runspaces.runspacefactory]::CreateRunspace()
$rs.open()
$ps = [System.Management.Automation.PowerShell]::Create()
$ps.Runspace = $rs
$ps.Dispose()
"Before Dispose"
$rs.Dispose()
"After Dispose"
Stop-Transcript
```
## Expected behavior

No errors, the whole transcript (including "After Dispose") should be in the `foo.txt` file
## Actual behavior

```
Stop-Transcript : An error occurred stopping transcription: The host is not currently transcribing.
At line:1 char:1
+ Stop-Transcript
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Stop-Transcript], PSInvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,Microsoft.PowerShell.Commands.StopTranscriptCommand
```

"After Dispose" is not in the `foo.txt` file
## Environment data

Windows.

``` powershell
> $PSVersionTable
Name                           Value
----                           -----
PSEdition                      Core
PSVersion                      6.0.0-alpha
CLRVersion
GitCommitId                    v6.0.0-alpha.10
WSManStackVersion              3.0
BuildVersion                   3.0.0.0
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

 Also verfied in inbox

```
Name                           Value
----                           -----
PSVersion                      5.1.14393.187
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.187
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

cc @adityapatwardhan @LeeHolmes @PaulHigin

**Comment by Fitzroy87** [comment]
@vors - does this issue account for the undesired behaviour documented in this uservoice post? https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/14745750-ps-5-0-bug-transcript-stops-after-restarting-a-re

**Comment by vors** [comment]
@Fitzroy87 my wild guess is yes. These two are likely related.

**Comment by vors** [comment]
@Fitzroy87 the issue is still open, which mean that it's still present in the `master` branch.

**Comment by SteveL-MSFT** [comment]
@chunqingchen I'm assigning this to you since you're already touching the transcription code

**Comment by chunqingchen** [comment]
This issue has been resolved fixed and verified

**Comment by potatoqualitee** [comment]
Is this only going to be fixed in PS6?

![image](https://user-images.githubusercontent.com/8278033/49687291-33f47d00-fb01-11e8-9117-22afb893dbee.png)

![image](https://user-images.githubusercontent.com/8278033/49687316-86359e00-fb01-11e8-8d86-933e06bd9d00.png)

Is there anything we can do locally to fix it? Perhaps some override?

**Comment by potatoqualitee** [comment]
omg uh, i have no idea how i unassigned anyone 😐 sorry @chunqingchen !

**Comment by potatoqualitee** [comment]
I saw it was fixed in 6, just hoping it could mayyyybe get fixed in the version that most of our people use 🤞

**Comment by vexx32** [comment]
From what I've been told there's going to be basically no more fixes backported to PS5.1, I'm afraid.

Your best bet is to submit a request on the uservoice site for Windows PowerShell, but from what I've heard there are no guarantees anything more will be done with Windows PowerShell. 🙁

**Comment by MaximoTrinidad** [comment]
@vexx32 

Yes! There's no guarantees, but it helps identify bugs for PowerShell Core.

Bugs found in Windows PowerShell are been fix in PowerShell Core, as Windows PowerShell is complete. Microsoft was clear on this statement that they stop doing work in Windows PowerShell. So, 5.1 is the last version.

So, if there's any bug found in Windows PowerShell, it should repro in Core so it can be fix moving forward.

I have to say, now is a good time to truly test PowerShell Core, alongside Windows PowerShell, to help cleaning up what's missing.  As, down the road, PowerShell Core will substitute Windows PowerShell. 
:)

**Comment by vexx32** [comment]
Indeed, no argument there, but as has already been mentioned, this particular issue seems to have been fixed for Core already. 😄

**Comment by SteveL-MSFT** [comment]
Since this specific issue is security related, we did make a fix in Windows PowerShell 5.1, but it'll only be available in newest Win10 builds.

**Comment by SteveL-MSFT** [comment]
The last two digits in the version are updated automatically by the build system.  You should just consider it magic and not rely on it.  "Newest" here specifically means I believe the fix was checked in late last week so unless whenever that builds goes out to the Insider flights.  Without going into details, it's complicated how a fix we make in our working branch in Windows ends up into a flighted build.  It can take weeks.

**Comment by alexandair** [comment]
I hope PowerShell team is aware how very confusing all this is. And, if it's confusing to someone who is involved as much as I am, I don't understand how regular PowerShell users can keep track on all this. 
Version numbers that are not actually representing builds, inconsistent version numbers... If something is fixed in the insider build, that's not actually fixed for the most users. Majority of users care about the production-ready builds, and insider builds are not ready for a production. 1809 build showed us that even that one wasn't ready for a couple of months. :(

**Comment by potatoqualitee** [comment]
That is good news, thank you @SteveL-MSFT! I will let people know.

**Comment by PaulHigin** [comment]
@alexandair Yes, this is unfortunately a confusing process.  The fix was ported to a low level internal branch on 12/12 last week, and as @SteveL-MSFT mentioned, will propagate to a vNext flighting branch in a few weeks.

I doubt the fix would meet the bar for back porting to servicing branches (i.e., a patch), especially since the change in behavior can be viewed as a breaking change.

**Comment by thecliguy** [comment]
@paulhigin How is fixing it a breaking change when in fact the introduction of this issue was a breaking change for scripts written against all prior versions of Powershell?

The particular effect of this issue that I'm referring to is documented here (a UserVoice issue I raised in 2016): https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/14745750-ps-5-0-bug-transcript-stops-after-restarting-a-re

**Comment by HammadKamran** [comment]
Hi, the issue seems to have poped back up. 
![image](https://user-images.githubusercontent.com/49006960/82059886-89519800-96be-11ea-9ecc-f08612aed86e.png)
![image](https://user-images.githubusercontent.com/49006960/82060001-a8502a00-96be-11ea-8a13-2b8aca0a9601.png)
