### ISSUE TITLE
winget version does not match release version

### ISSUE THREAD

**Issue by alirobe** [PowerShell/PowerShell#26261]
### Prerequisites

- [x] Write a descriptive title.
- [x] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [x] Search the existing issues.
- [x] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [x] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

https://winget.run/pkg/Microsoft/PowerShell

Latest version listed is 7.3.3.

I am getting the the 'new stable release available' notification in PowerShell. 

If I `--Force` a winget install, I get 7.5.3 again, which is still not the latest version.

I am in Australia (GMT+10), so it's possible that this is something that only happens because I am a day ahead?

### Expected behavior

```console
winget install --id Microsoft.Powershell --source winget --force
Found PowerShell [Microsoft.PowerShell] Version 7.5.4.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/PowerShell/PowerShell/releases/download/v7.5.4/PowerShell-7.5.4-win-x64.msi
```

### Actual behavior

```console
winget install --id Microsoft.Powershell --source winget --force
Found PowerShell [Microsoft.PowerShell] Version 7.5.3.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/PowerShell/PowerShell/releases/download/v7.5.3/PowerShell-7.5.3-win-x64.msi
```

### Environment data

```powershell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.5.3
PSEdition                      Core
GitCommitId                    7.5.3
OS                             Microsoft Windows 10.0.26100
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### OS Data

```powershell
Version    Caption
-------    -------
10.0.26100 Microsoft Windows 11 Enterprise
```

### Windows update log

```markdown
N/A
```

**Comment by weitzhandler** [comment]
Same here, when opening the terminal I see:

>PowerShell 7.5.3
>
>   A new PowerShell stable release is available: v7.5.4
   Upgrade now, or check out the release page at:
     https://aka.ms/PowerShell-Release?tag=v7.5.4
>
>Loading personal and system profiles took 1105ms.

However:

> &gt;winget update microsoft.powershell
>No available upgrade found.
>No newer package versions are available from the configured sources

And this happens every time there a new PS release.  
You probably want to include pushing to winget as part of the release pipeline.

**Comment by zeroquinc** [comment]
> And this happens every time there a new PS release. You probably want to include pushing to winget as part of the release pipeline.

Yes please. Same issue here.

**Comment by CVET-TJGutjahr** [comment]
I noticed this as well. Wasn't sure if it was due to a delay in getting the new update entry merged into the winget package feed (PR merge?) or if it was just missed.

**Comment by kilasuit** [comment]
Awaiting the following PR's to be merged in the Winget-Pkgs repo & as noted there is always a delay in the process for these below PR's to be merged and the packages available via winget - something that is slowly gettign better I may add.

https://github.com/microsoft/winget-pkgs/pull/305258
https://github.com/microsoft/winget-pkgs/pull/305230

As such this issue is actually an external issue so marking this Resolution-External for now

**Comment by kilasuit** [comment]
Personal Suggestion is to retry upgrading again around this time tomorrow. If still any issues then the team can investigate and provide additional updates but I expect it should be in the winget feed by then

**Comment by daxian-dbw** [comment]
BTW, the website https://winget.run is not owned by Microsoft.

**Comment by anamnavi** [comment]
Hi all, sorry for the inconvenience here, had to wait for the PR for the new version to get merged in winget side. `7.5.4.0` is now merged in and should be available via winget.

**Comment by alirobe** [comment]
As a UX thing, would it be possible only to inform me if I have a version that is more than a week stale? That would make it actionable information. With the various distribution methods for PS (brew, apt, winget, etc) expecting immediate availability of the update may be unrealistic anyway.  I don't like having warnings I have to train myself to ignore for a while... 

For me, it's not that bad, but this impacts everyone who uses powershell daily, on a per-release basis, and it's training me to ignore errors and alerts. It's a part of the UX that is worth getting right. If you're worried about security, you could have a flag for an urgent update for when waiting is too slow.

Also, the update isn't installing for me. 

```pwsh
winget update --id Microsoft.PowerShell --version 7.5.4.0 --force
OR 
winget update --id Microsoft.PowerShell 
No installed package found matching input criteria.
```

I assume this will resolve tomorrow or something.

```
winget list --upgrade-available 
Name                   Id                        Version Available Source
-------------------------------------------------------------------------
NVM for Windows 1.1.12 CoreyButler.NVMforWindows 1.1.12  1.2.2     winget
PowerShell 7.5.3.0-x64 Microsoft.PowerShell      7.5.3.0 7.5.4.0   winget
3 upgrades available.
```

**Comment by xtqqczze** [comment]
> BTW, the website https://winget.run is not owned by Microsoft.

winget.run is no longer updated, it is [abandoned](https://github.com/winget-run/wingetdotrun/issues/53).

**Comment by CVET-TJGutjahr** [comment]
> As a UX thing, would it be possible only to inform me if I have a version that is more than a week stale? That would make it actionable information. With the various distribution methods for PS (brew, apt, winget, etc) expecting immediate availability of the update may be unrealistic anyway. I don't like having warnings I have to train myself to ignore for a while...
> 
> For me, it's not that bad, but this impacts everyone who uses powershell daily, on a per-release basis, and it's training me to ignore errors and alerts. It's a part of the UX that is worth getting right. If you're worried about security, you could have a flag for an urgent update for when waiting is too slow.
> 
> Also, the update isn't installing for me.
> 
> winget update --id Microsoft.PowerShell --version 7.5.4.0 --force
> OR 
> winget update --id Microsoft.PowerShell 
> No installed package found matching input criteria.
> I assume this will resolve tomorrow or something.
> 
> ```
> winget list --upgrade-available 
> Name                   Id                        Version Available Source
> -------------------------------------------------------------------------
> NVM for Windows 1.1.12 CoreyButler.NVMforWindows 1.1.12  1.2.2     winget
> PowerShell 7.5.3.0-x64 Microsoft.PowerShell      7.5.3.0 7.5.4.0   winget
> 3 upgrades available.
> ```

I had the same issue, I ended up just installing it again while it was already installed.

`winget install -e --id Microsoft.PowerShell -a x64` and it installed the 7.5.4.0 version and it was updated...

**Comment by daxian-dbw** [comment]
> As a UX thing, would it be possible only to inform me if I have a version that is more than a week stale? That would make it actionable information.

@alirobe I think this is a good suggestion. Can you please open a new issue for it? We want to make the update notification more useful instead of confusing to users.

**Comment by alirobe** [comment]
Done ^


Incidentally @CVET-TJGutjahr's idea didnt work. So I gave up with winget, downloaded the installer manually, and told it to keep updated via windows update.

**Comment by doctordns** [comment]
While WInGet seems to be an approved method of installing PowerShell, it is a developer power toy I choose not to use. The WinGet team chose to make a tool that had little compatibility as possible with PowerShell. I see little to nothing in WinGet that I can't do as easily by other means. Mileage varies. and it remains unsupported in Windows Server where alternative means are needed anyway.

Personally, I use the `install-powershell.ps1` script from the PowerShell github repo. You can do it one of two ways: You can invoke this directly from Github, like this:

```powershell
 Invoke-Expression "& { $(Invoke-RestMethod 'https://aka.ms/install-powershell.ps1') }
```
Or download the script to a local folder and run it from there.

The benefit of this approach is that as soon as you see the warning message, you can just run the script and updater PowerShell. 

It just works.

**Comment by karofsky** [comment]
> > As a UX thing, would it be possible only to inform me if I have a version that is more than a week stale? That would make it actionable information. With the various distribution methods for PS (brew, apt, winget, etc) expecting immediate availability of the update may be unrealistic anyway. I don't like having warnings I have to train myself to ignore for a while...
> > For me, it's not that bad, but this impacts everyone who uses powershell daily, on a per-release basis, and it's training me to ignore errors and alerts. It's a part of the UX that is worth getting right. If you're worried about security, you could have a flag for an urgent update for when waiting is too slow.
> > Also, the update isn't installing for me.
> > winget update --id Microsoft.PowerShell --version 7.5.4.0 --force
> > OR
> > winget update --id Microsoft.PowerShell
> > No installed package found matching input criteria.
> > I assume this will resolve tomorrow or something.
> > ```
> > winget list --upgrade-available 
> > Name                   Id                        Version Available Source
> > -------------------------------------------------------------------------
> > NVM for Windows 1.1.12 CoreyButler.NVMforWindows 1.1.12  1.2.2     winget
> > PowerShell 7.5.3.0-x64 Microsoft.PowerShell      7.5.3.0 7.5.4.0   winget
> > 3 upgrades available.
> > ```
> 
> I had the same issue, I ended up just installing it again while it was already installed.
> 
> `winget install -e --id Microsoft.PowerShell -a x64` and it installed the 7.5.4.0 version and it was updated...

this works for me

**Comment by alirobe** [comment]
> While WInGet seems to be an approved method of installing PowerShell, it is a developer power toy I choose not to use. The WinGet team chose to make a tool that had little compatibility as possible with PowerShell. I see little to nothing in WinGet that I can't do as easily by other means. Mileage varies. and it remains unsupported in Windows Server where alternative means are needed anyway.

In 2022, WinGet isn’t supported out of the box. But in 2025, it’s included and fully supported with growing adoption, especially in managed environments that use Intune or Endpoint Manager. 
 
- [New in Windows Server 2025 - WinGet](https://learn.microsoft.com/en-us/windows-server/get-started/whats-new-windows-server-2025#winget)
- [Windows Package Manager for Enterprise Security](https://learn.microsoft.com/windows/package-manager/#windows-package-manager-for-enterprise-security)
- [Using WinGet with Intune (Practical 365)](https://practical365.com/using-winget-with-intune/)

Conceptually, package management is a long-established practice in Linux and other OSes for reliable, traceable deployment. WinGet is bringing that same model to Windows in a supported, enterprise-ready way, and it is the future. I do get where you are coming from, and I am glad that works for you. I have switched to the way you are doing it. I still think I shouldn't have to. I don't want PowerShell to be a special snowflake. If I can update all the packages on my PC with one command, I would rather just have it be part of that process, and I guess that's just down to preference.

**Comment by DarthKevin** [comment]
> > 
> > I had the same issue, I ended up just installing it again while it was already installed.
> > `winget install -e --id Microsoft.PowerShell -a x64` and it installed the 7.5.4.0 version and it was updated...
> 
> this works for me

That still doesn't work for me.  Even after verifying Winget itself was up to date and running
`winget source update`
to ensure sources were also up to date.  

```
PS C:\Admin Tools\Scripts> winget install -e --id Microsoft.PowerShell -a x64
Found an existing package already installed. Trying to upgrade the installed package...
No available upgrade found.
No newer package versions are available from the configured sources.
PS C:\Admin Tools\Scripts> pwsh -v
PowerShell 7.5.3
```
